### PR TITLE
Surely we should be adding 1, not 0?

### PR DESCRIPTION
**Pull request by tshowalter**
The thread safety counter is being incremented by zero...

### CODE REVIEW

**Comment by rivera-ernesto** [comment]
Seems logic.

> `atomic add, incre-ment, increment,
     ment, decrement, or, and, xor, compare and swap, test and set, test and
     clear, spinlocks, and lockless queues`

> `OSAtomicAdd32(int32_t theAmount, volatile int32_t *theValue);`

Wondering why it was unnoticed and what was the result of this bug.

**Comment by tshowalter** [comment]
Well, in our case the result was a random crash in NSDateFormatter, maybe one time in 30.

**Comment by rivera-ernesto** [comment]
Let's give it a try. Could be related to #53.

**Comment by erysaj** [comment]
Guys this change is totally wrong...
`_atomicLoggerCount` is counting (as variable name is implying) the loggers current formatter instance has been added to (hence atomic increments/decrements in corresponding delegate methods).
Now take a look at `stringFromDate:`. The method must deal with the fact that the NSDateFormatter is not thread safe (I've recently stumbled upon a related issue #33; I also bet that it is the crash @tshowalter experienced).
One of proposed (and allegedly working) solutions was to use `[NSThread threadDictionary]` to store date formatter instances per thread. Implementation of `DDDispatchQueueLogFormatter` tries to optimise overhead: if formatter is used by only 1 logger there is no need in thread-safety precautions, as logger processes log message on a serial dispatch queue.
To decide which approach to take you can't just read an ivar, it is modified by atomic functions so naturally you need a special way to read its value (with memory barrier). The simplest way seems to be just adding  `0` atomically (`OSAtomicAdd*` returns a result). Incrementing by `1`is a logical mistake: `stringFromDate:` is called on each log message and as a result `_atomicLoggerCount` will be nowhere close to the actual logger count.

Still this hybrid approach does not seem to work. Statistics for the app I develop shows crashes in `NSDateFormatter` and I can't figure out how exactly it happens considering all the taken measures
(we use a custom formatter that follows the same implementation pattern). My fix was to create
a separate formatter for each logger, though the fix is not in production yet, so I can't tell for sure that it helped. I think an acceptable solution would be to specify if thread-safety is required from formatter in its constructor and add assertion for the situation when users adds non-threadsafe instance to the 2nd logger.

P.S. while writing this comment I looked through reference issue and found [this wiki article](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Documentation/CustomFormatters.md)

**Comment by rivera-ernesto** [comment]
We really have a long-standing problem with this formatter so any contribution is greatly appreciated.

**Comment by rivera-ernesto** [comment]
Related issues and pull requests: https://github.com/CocoaLumberjack/CocoaLumberjack/search?q=NSDateFormatter&type=Issues&utf8=✓

**Comment by erysaj** [comment]
> any contribution is greatly appreciated.

I've created #621 to show what I had in mind

**Comment by bpoplauschi** [comment]
@erysaj Only now I totally understood your comments. Indeed, changing
`int32_t loggerCount = OSAtomicAdd32(0, &_atomicLoggerCount);` to `int32_t loggerCount = OSAtomicAdd32(1, &_atomicLoggerCount);` was a big mistake. That was only a pseudo-sync mechanism to make sure we read the correct value. But I'm not sure it's 100% safe. The big minus here was this was not properly documented.

Also, agreeing with the solution discussed on your PR. I will participate to that but I wanted this thread to show the actual mistake.

**Pull request merged**
