### PR TITLE
Repo cleanup #trivial

### PR DESCRIPTION
**Pull request by ffried**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/CocoaLumberjack/)
* [x] I have searched for a similar pull request in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have added the required tests to prove the fix/feature I am adding
* [x] I have updated the documentation (if necessary)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / refers to the following issues: n/a

### Pull Request Description

This updates the GitHub actions workflows to use the latest versions of some actions. Also, selecting Xcode now happens via a separate action instead of hard-coding the path inside a script file.
The Dependabot config file was also adjusted to not directly assign issues to me and run whenever GitHub seems fit (no time defined) (-> the original file was copied from one of our repos, that's why there were these settings in there)

### CODE REVIEW

**Review by sushichop — APPROVED** [review]
> (-> the original file was copied from one of our repos, that's why there were these settings in there)

I see🙂

**Comment by ffried** [comment]
@bpoplauschi @rivera-ernesto I've updated the devices on which tests are run. Because of that, the following two, currently required checks no longer exist:

image


Can either of you guys please remove them in the branch protection rule settings and add the updated versions:
```
Unit Tests / xcode (Swift Tests, platform=iOS Simulator,OS=latest,name=iPhone 12 Pro)
Unit Tests / xcode (iOS Tests, platform=iOS Simulator,name=iPhone 12 Pro,OS=latest, iOS Tests/DDFileLoggerPerformanceTests)```

**Comment by bpoplauschi** [comment]
@ffried I made the suggested changes, please let me know if I missed anything :)

**Comment by ffried** [comment]
@bpoplauschi Thanks! Yep, all checks are now green as it should be! :)

**Pull request merged**
