### PR TITLE
Update to Xcode 8.1 and Swift 3.0.1

### PR DESCRIPTION
**Pull request by sushichop**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/CocoaLumberjack/)
* [x] I have searched for a similar pull request in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)

* [N/A] I have added the required tests to prove the fix/feature I am adding
--> Because Swift 3.0 and Swift 3.0.1 is almost same and I confirmed `pod lib lint` and `travis ci test` passed.

* [x] I have updated the documentation (if necesarry)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / reffers to the following issues: #814 

### Pull Request Description

I updated to Xcode 8.1 and made CocoaLumberjack Library support both Swift 3.0 and Swift 3.0.1.

Note.
I removed xcconfig that sets SWIFT_VERSION in podspec file.
As @benasher44 says at #814, now  SWIFT_VERSION should not be set by podspec but by developers.

For example,
Developers who use Xcode 8.0 will set SWIFT_VERSION 3.0 with post_install hook.
Developers who use Xcode 8.1 will set SWIFT_VERSION 3.0.1 with post_install hook.

This is a common and preferred way to integrate CocoaPods with Xcode 8.0+.
In order to do it, I also updated README.
For details, pls check the latest commit(https://github.com/CocoaLumberjack/CocoaLumberjack/commit/3069fcf2bf2ddbf1f9edf76d6ef05efdcdd329e1).

Thanks.

### CODE REVIEW

**Comment by benasher44** [comment]
@sushichop thanks for doing this! Actually, developers shouldn't need to use a `post_install` hook at all. Updated versions of CocoaPods use the `SWIFT_VERSION` set in your main project as the version to use when building your pods, so a `post_install` hook to set this setting in particular shouldn't be necessary.

**Comment by sushichop** [comment]
Oh, I didn't know that. Thanks.
At last I understand correctly what you mean.

I removed `post_install` hook from README and I confirmed it works as you say. 
See the above commit(https://github.com/CocoaLumberjack/CocoaLumberjack/pull/816/commits/ee3c9ddcb66c24f62626adba60d7e07c5fee4830).

Thanks again.

**Comment by sushichop** [comment]
@benasher44
Additional Info.
I also have checked https://github.com/CocoaPods/CocoaPods/issues/6067, https://github.com/CocoaPods/CocoaPods/pull/6068.

And for now CocoaLumberjack CI Test use Cocoapods 1.1.1.
Then, in my main project, I confirmed by setting SWIFT_VERSION with project level(without xcconfig).

**Comment by benasher44** [comment]
Looks good to me!

**Comment by sushichop** [comment]
@rivera-ernesto @bpoplauschi
Could you review this PR?

FYI 
Xcode 8.2 was released a few days ago, but travis-ci seems to have trouble with Xcode.
See https://github.com/travis-ci/travis-ci/issues/7031. Actually I experienced the same error with Xcode 8.2.
So I think you had better keep using Xcode 8.1 for a while. 

Cheers.

**Comment by rivera-ernesto** [comment]
Thanks!

**Pull request merged**
