### PR TITLE
Enable Build Libraries for Distribution

### PR DESCRIPTION
**Pull request by nhatlee**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/CocoaLumberjack/)
* [x] I have searched for a similar pull request in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have run the tests and they pass
This merge request fixes / refers to the following issues: [Module compiled with Swift 5.x cannot be imported by the Swift 5.x.x compiler .On Swift forum](https://forums.swift.org/t/module-compiled-with-swift-5-1-cannot-be-imported-by-the-swift-5-1-2-compiler/30431)

### CODE REVIEW

**Comment by ffried** [comment]
@nhatlee This topic was discussed in #1110 where we also decided to have a separate branch that will integrate this kind of "trial-like" until we're sure we don't get any side-effects from this.
I've just rebased the branch (`binary_framework`) to be up to date with master.

**Comment by OSSPolice** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">The Carthage project was modified but CocoaPods podspec wasn’t. Did you forget to update the podspec?</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Xcode settings need to remain in Configs/*.xcconfig. Please move BUILD_LIBRARY_FOR_DISTRIBUTION to the xcconfig file</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by rodmaz** [comment]
Even using `binary_framework`, the problem persists:

```
Module 'CocoaLumberjackSwift' was not compiled with library evolution support; using it means binary compatibility for 'MyTarget' can't be guaranteed.
```

**Comment by ffried** [comment]
Yep, it mentioned too in #1110.

**Pull request closed without merging**
