### PR TITLE
Fix import statement in README.md file

### PR DESCRIPTION
**Pull request by JimRoepcke**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](http://cocoadocs.org/docsets/CocoaLumberjack/)
* [ ] I have searched for a similar pull request in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/pulls) and found none

* [ ] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [ ] I have added the required tests to prove the fix/feature I am adding
* [ ] I have updated the documentation (if necessary)
* [ ] I have run the tests and they pass
* [ ] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / refers to the following issues: ...

### Pull Request Description

The module name is CocoaLumberjack.Swift not CocoaLumberjackSwift

### CODE REVIEW

**Comment by ffried** [comment]
@JimRoepcke Are you integrating CocoaLumberjack using CocoaPods? I'm asking because for manual integration, the import statement is correct in the current README (the module name is `CocoaLumberjackSwift`).
There has been a recent restructuring of the Pod, so maybe this is a side effect of this. If this is the case, would you mind making this distinction in the README, too?

**Comment by bpoplauschi** [comment]
I suggest we make this info explicit in the Readme.
Like we do for the different install methods

**Comment by mackuba** [comment]
`import CocoaLumberjack` also works. `import CocoaLumberjackSwift` definitely doesn't work when imported from Pods.

**Comment by sushichop** [comment]
I'm closing this PR in favor of #1108 .
Please feel free to reopen it or report a issue if you have any questions.
Thanks.

**Comment by bpoplauschi** [comment]
@JimRoepcke Thanks a lot for showing interest and contributing to CocoaLumberjack! I know it's been a while since you contributed, but we would like to invite you to become a maintainer – no pressure to accept! You can pitch in with what seems comfortable: comment on open issues/PRs, triage, improve documentation, write your own PRs. Let me know if you are interested.

**Pull request closed without merging**
