### PR TITLE
Merged framework targets + using xcconfig + deployment target iOS 8 and Mac OS 10.10

### PR DESCRIPTION
**Pull request by bpoplauschi**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/CocoaLumberjack/)

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have updated the documentation (if necessary)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / refers to the following issues: ...

### Pull Request Description

- Xcode 10 (already supported)
- merged the framework targets into multi-platform ones
- using xcconfig for most of the configurations (Lumberjack.xcodeproj + Tests.xcodeproj + Demos) - only adding setting in xcodeproj where they are not valid for all the other targets
- set deployment target to iOS8 and Mac OS 10.10 - also cleaned up some branched code for the earlier versions
- updated Travis scripts

### CODE REVIEW

**Comment by lolgear** [comment]
@bpoplauschi could you also include separation of framework target and integration target?

https://github.com/CocoaLumberjack/CocoaLumberjack/issues/954#issuecomment-429794812

**Comment by bpoplauschi** [comment]
@lolgear I will look into this

**Comment by bpoplauschi** [comment]
@CocoaLumberjack/collaborators please review this PR - I would like to merge it sooner rather than later so @sushichop can work on top of it.

**Comment by bpoplauschi** [comment]
@lolgear I haven't done the splitting of targets into 2 projects. I thought that will just make this PR even longer to complete. Perhaps we/you can do that in a separate one after this one is merged.

**Comment by lolgear** [comment]
@bpoplauschi could you create milestone for "refactoring"?

**Comment by sushichop** [comment]
@bpoplauschi 
Great Job! I gladly merge this PR

**Comment by bpoplauschi** [comment]
Thanks @sushichop 

@lolgear what do you mean by a milestone for refactoring? Like a major release 4.x where we can refactor? We can start with a `4.x` branch and work there. What ideas of refactoring do you have, cause we should talk in advance. For moving the app integration targets to a separate project we don't need a major refactoring.

**Comment by bpoplauschi** [comment]
@diederich 

> I might break for some people, but we probably won't find out without merging.

Do you mean for our users? If so, what do you think it will break? Other than removing support for iOS 6 and 7 and Mac OS X 10.8 and 10.9? :)

> I like xcconfig files. If you want something that has more comments, maybe you can copy from here: https://github.com/jspahrsummers/xcconfigs/blob/master/Base/Common.xcconfig

Thanks for the suggestion. I think it's a lot clearer if they have comments, so I added them: e97da34 - committed directly since it only adds comments.

**Comment by lolgear** [comment]
@bpoplauschi

Refactoring or 3.5.0, it doesn't matter. New milestone is needed. "Refactoring-at-3.5.0" would be better, because all intensions in 3.5.0 are directed to refactoring and cleanup. ( and fix bugs, btw )

**Comment by bpoplauschi** [comment]
@lolgear I added the 3.5.0 milestone - we only have a few remaining things to do before we can release it.

**Pull request merged**
