### PR TITLE
Port Travis configuration to GitHub actions

### PR DESCRIPTION
**Pull request by ffried**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/CocoaLumberjack/)
* [x] I have searched for a similar pull request in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have added the required tests to prove the fix/feature I am adding
* [x] I have updated the documentation (if necessary)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / refers to the following issues: -

### Pull Request Description

This attempts to ditch Travis and use GitHub Actions instead. Travis seems to have become slow in adopting new OS' (e.g. there's still no macOS 10.15).

A few things to note:
- I've used [our own action](https://github.com/sersoft-gmbh/xcodebuild-action) for running `xcodebuild` commands. I found this easier to maintain, but feel like it's worth mentioning since I'm also developing said action. I'd have no issue with converting back to manual command execution if you guys prefer that.
- I've split the tasks into multiple workflow files. This makes it easier to see what is what.
- This PR is still WIP since I need to test whether a few things work. Also, I'll eventually need the support of one of the repo admin to make the final switch (setting required PR checks, maybe add the codecov token to secrets).

### CODE REVIEW

**Comment by ffried** [comment]
Oh I just hope GitHub only sends all those emails to me and not all of you guys 🙈

**Comment by bpoplauschi** [comment]
Wow, looks very promising

**Comment by ffried** [comment]
@bpoplauschi Thanks! I've had good experiences with GitHub actions in the last few days (converted all of our public and private repos).

Currently fighting with the watchOS build. Seems like it broke as of Xcode 11.4. It's what causes the watchOS integration build to fail (and thus some other integration builds to be cancelled).

**Comment by ffried** [comment]
Alright. I'm done with the things I can do myself.

@bpoplauschi Would you mind doing some changes to the repository settings?
The following changes would need to be done:

[ ] Add a [secret](https://github.com/CocoaLumberjack/CocoaLumbrejack/settings/secrets) named `CODECOV_TOKEN` adding the token from codecov's [settings page](https://codecov.io/gh/CocoaLumberjack/CocoaLumberjack/settings).
[ ] Consider integration of Codecov app (I've opened a request against the CocoaLumberjack team).
[ ] Change the required PR checks from Travis to GitHub actions. Unfortunately (or fortunately?), GitHub currently lists **all** run jobs as a potential required check. To simplify things, I'd only require everything under `Unit Tests/*` and `Validations/*`. The `Integration Builds` _might_ be of interest, but IMHO not _required_ per se. `Library Builds` are not that interesting. If they fail, `Unit Tests` will fail, too.
[ ] Remove Travis from the repository and/or account. I'm not sure how deeply travis is integrated in this account. Maybe it's just a [hook](https://github.com/CocoaLumberjack/CocoaLumberjack/settings/hooks) . Maybe it's also in [Third-party access](https://github.com/organizations/CocoaLumberjack/settings/oauth_application_policy) and/or [GitHub apps](https://github.com/organizations/CocoaLumberjack/settings/installations).

Of course, you might want to review and merge this PR first 🙃

**Comment by lolgear** [comment]
@ffried CODECOVID_TOKEN
Sorry

**Comment by ffried** [comment]
@lolgear Sorry, this PR is virus-free 😉

**Comment by lolgear** [comment]
@ffried Reviewing this PR grants you immunity.

**Comment by bpoplauschi** [comment]
@ffried do we really want to have 49 checks running for every build? Are all of those running in parallel?
I didn't dig into GitHub actions, but they must have some limitation to running

**Comment by ffried** [comment]
@bpoplauschi We have projects with 100+ checks running. The limit is 256 last I checked.
GitHub lets 5 macOS runners run in parallel. In total, I think GitHub action is now faster than Travis was before due to this.
We could think about letting the demos only build on master. But I’d postpone that to a later PR once we’ve gained a little more experience with how GitHub actions works in our case.
What do you think?

**Comment by bpoplauschi** [comment]
I started looking into GitHub actions, found this article https://medium.com/rosberryapps/github-actions-ci-for-swift-projects-c129baceed1a

A few questions:

> Workflows must contain at least one job. ... It is possible to run up to 20 jobs concurrently per repository across all workflows.

- I wonder why we can run more than those 20 concurrent jobs. Or does GitHub just run 20 concurrent and keep the others waiting until slots are freed.

- Is there a mechanism to specify which OSX configuration we want to run on - something like Travis has `osx_image: xcode11`?

**Comment by bpoplauschi** [comment]
PS: those are just questions, I think the PR looks good and I want to merge it

**Comment by bpoplauschi** [comment]
> Alright. I'm done with the things I can do myself.
> 
> @bpoplauschi Would you mind doing some changes to the repository settings?
> The following changes would be needed:
> 
> * [x]  Add a [secret](https://github.com/CocoaLumberjack/CocoaLumbrejack/settings/secrets) named `CODECOV_TOKEN` adding the token from codecov's [settings page](https://codecov.io/gh/CocoaLumberjack/CocoaLumberjack/settings).
> * [x]  Consider integration of Codecov app (I've opened a request against the CocoaLumberjack team).
> * [ ]  Change the required PR checks from Travis to GitHub actions. Unfortunately (or fortunately?), GitHub currently lists **all** run jobs as a potential required check. To simplify things, I'd only require everything under `Unit Tests/*` and `Validations/*`. The `Integration Builds` _might_ be of interest, but IMHO not _required_ per se. `Library Builds` are not that interesting. If they fail, `Unit Tests` will fail, too.
> * [ ]  Remove Travis from the repository and/or account. I'm not sure how deeply travis is integrated in this account. Maybe it's just a [hook](https://github.com/CocoaLumberjack/CocoaLumberjack/settings/hooks) . Maybe it's also in [Third-party access](https://github.com/organizations/CocoaLumberjack/settings/oauth_application_policy) and/or [GitHub apps](https://github.com/organizations/CocoaLumberjack/settings/installations).
> 
> Of course, you might want to review and merge this PR first 🙃

I've done 1 and 2, I guess the other two will be done once I merge this PR, right?

**Comment by ffried** [comment]
> I started looking into GitHub actions, found this article https://medium.com/rosberryapps/github-actions-ci-for-swift-projects-c129baceed1a
> 
> 
> 
> A few questions:
> 
> 
> 
> > Workflows must contain at least one job. ... It is possible to run up to 20 jobs concurrently per repository across all workflows.
> 
> 
> 
> - I wonder why we can run more than those 20 concurrent jobs. Or does GitHub just run 20 concurrent and keep the others waiting until slots are freed.
> 
> 
> 
> - Is there a mechanism to specify which OSX configuration we want to run on - something like Travis has `osx_image: xcode11`?

@bpoplauschi 
- 20 concurrent jobs are possible for Linux runners. For macOS it caps out at 5. Which is why I use Linux wherever possible. In our Setup this would only be possible for danger I guess.
Also, these limits are per repository. So we can’t create 10 workflow files with 5 jobs each and have 50 concurrent runs this way.

- macOS runners have various Xcode versions installed. I usually do the Xcode-select directly in the file. In our case I opted for creating a small script for that, to make it easier to upgrade Xcode versions. It’s in the Scripts folder and is executed directly after checking out the repo in all jobs.

**Comment by ffried** [comment]
> > Alright. I'm done with the things I can do myself.
> 
> > 
> 
> > @bpoplauschi Would you mind doing some changes to the repository settings?
> 
> > The following changes would be needed:
> 
> > 
> 
> > * [x]  Add a [secret](https://github.com/CocoaLumberjack/CocoaLumbrejack/settings/secrets) named `CODECOV_TOKEN` adding the token from codecov's [settings page](https://codecov.io/gh/CocoaLumberjack/CocoaLumberjack/settings).
> 
> > * [x]  Consider integration of Codecov app (I've opened a request against the CocoaLumberjack team).
> 
> > * [ ]  Change the required PR checks from Travis to GitHub actions. Unfortunately (or fortunately?), GitHub currently lists **all** run jobs as a potential required check. To simplify things, I'd only require everything under `Unit Tests/*` and `Validations/*`. The `Integration Builds` _might_ be of interest, but IMHO not _required_ per se. `Library Builds` are not that interesting. If they fail, `Unit Tests` will fail, too.
> 
> > * [ ]  Remove Travis from the repository and/or account. I'm not sure how deeply travis is integrated in this account. Maybe it's just a [hook](https://github.com/CocoaLumberjack/CocoaLumberjack/settings/hooks) . Maybe it's also in [Third-party access](https://github.com/organizations/CocoaLumberjack/settings/oauth_application_policy) and/or [GitHub apps](https://github.com/organizations/CocoaLumberjack/settings/installations).
> 
> > 
> 
> > Of course, you might want to review and merge this PR first 🙃
> 
> 
> 
> I've done 1 and 2, I guess the other two will be done once I merge this PR, right?

Yep, the last two need to be done after merging... 🙂

**Comment by bpoplauschi** [comment]
Awesome @ffried thanks for doing this and for clearing up those questions.
Let's 🚢 it :)

**Comment by ffried** [comment]
@bpoplauschi Thanks for reviewing and merging!

**Comment by bpoplauschi** [comment]
I think I covered the last 2 (just disabled Travis for now). Let's monitor this

> * [x]  Change the required PR checks from Travis to GitHub actions. Unfortunately (or fortunately?), GitHub currently lists **all** run jobs as a potential required check. To simplify things, I'd only require everything under `Unit Tests/*` and `Validations/*`. The `Integration Builds` _might_ be of interest, but IMHO not _required_ per se. `Library Builds` are not that interesting. If they fail, `Unit Tests` will fail, too.
> * [x]  Remove Travis from the repository and/or account. I'm not sure how deeply travis is integrated in this account. Maybe it's just a [hook](https://github.com/CocoaLumberjack/CocoaLumberjack/settings/hooks) . Maybe it's also in [Third-party access](https://github.com/organizations/CocoaLumberjack/settings/oauth_application_policy) and/or [GitHub apps](https://github.com/organizations/CocoaLumberjack/settings/installations).

**Pull request merged**
