### PR TITLE
Xcode9 updates

### PR DESCRIPTION
**Pull request by diederich**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/CocoaLumberjack/)
* [x] I have searched for a similar pull request in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/pulls) and found none

* [x ] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
[snip]
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

### Pull Request Description

Fixes a warning (error on -Werror) building with the current Xcode 9.
Also, add the warnings from Xcode 9 migration.

### CODE REVIEW

**Comment by rivera-ernesto** [comment]
Is this Xcode 8 backward compatible?

**Comment by diederich** [comment]
@rivera-ernesto yupyup, built with Xcode 8 to make sure.

**Comment by rivera-ernesto** [comment]
Nice. Just some small conflict solving and we're good then.

**Comment by diederich** [comment]
All green! 🎉 🎊😃

**Comment by sharon2sun** [comment]
@diederich  I tried 'pod update' today, but get no updates. CocoaLumberjack version is 3.2.0.  So I still get error in Xcode 9 beta 3. 
PS : My code is using Obj-C

**Comment by diederich** [comment]
@sharon2sun Sorry, I'm not using Cocoapods, but I guess this would need a version bump and adjusting the pod file. @rivera-ernesto maybe?

**Pull request merged**
