### PR TITLE
Update Swift log any support

### PR DESCRIPTION
**Pull request by Sunnyyoung**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/CocoaLumberjack/)
* [x] I have searched for a similar pull request in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have added the required tests to prove the fix/feature I am adding
* [x] I have updated the documentation (if necessary)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

### Pull Request Description

Update Swift log "Any" support, related issue: #1144

### CODE REVIEW

**Comment by bpoplauschi** [comment]
@ffried we can merge this, right?

**Comment by ffried** [comment]
@Sunnyyoung I've rebased the PR to get the latest changes to the Dangerfile to run the checks.

**Pull request merged**
