### PR TITLE
Update to Xcode 10 and Swift 4.2 complier

### PR DESCRIPTION
**Pull request by sushichop**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/CocoaLumberjack/)
* [x] I have searched for a similar pull request in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have added the required tests to prove the fix/feature I am adding
* [x] I have updated the documentation (if necessary)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

### Pull Request Description

Update to Xcode 10 and Swift 4.2 complier.
I set default SWIFT_VERSION to 4.2. 

In addition, this time I made CocoaLumberjack work with SWIFT_VERSION=4.2, SWIFT_VERSION=4.0, or SWIFT_VERSION=3.0 because some people still use Swift 3.
But if we don't need to support multi Swift versions, I'll change code to support only Swift 4.2. 

What do you think?

FYI
According to https://docs.swift.org/swift-book/GuidedTour/Compatibility.html,
Swift 4.2 complier with SWIFT_VERSION=3.0 means Swift 3.4.)

Thanks in advance.

### CODE REVIEW

**Comment by bpoplauschi** [comment]
Thanks for taking an interest in this @sushichop. I have started a branch for the Xcode10 support, but is not ready yet - diverged a bit into adding xcconfig files and merging some of the targets, but that is another story :)

For now, I'm not sure we need to go back with the Swift compatibility, as the current version 3.4.2 requires Swift 4.0. I think it's enough to bump that to 4.2. Also keeping 2 `pod lib lint` phases just makes the builds even longer, I don't think we need them.

**Comment by sushichop** [comment]
@bpoplauschi 
Thanks for your response.

> For now, I'm not sure we need to go back with the Swift compatibility, as the current version 3.4.2 requires Swift 4.0. I think it's enough to bump that to 4.2. Also keeping 2 `pod lib lint` phases just makes the builds even longer, I don't think we need them.

I agree with you.
Then, I changed code in order to support only Swift 4.2.

**Comment by sushichop** [comment]
@bpoplauschi 
Thanks. I have merged!

**Comment by bpoplauschi** [comment]
Good, I was waiting for the CI build to finish

**Pull request merged**
