### PR TITLE
Replace banned APIs with safe ones

### PR DESCRIPTION
**Pull request by ffried**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/CocoaLumberjack/)
* [x] I have searched for a similar pull request in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have added the required tests to prove the fix/feature I am adding
* [x] I have updated the documentation (if necessary)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / refers to the following issues: #1050 

### Pull Request Description

This replaces the banned APIs in the list mentioned in #1050 with their safe counterparts.

### CODE REVIEW

**Comment by lolgear** [comment]
@ffried 
Could you merge #1054 first? ( If it is necessary ).

**Comment by ffried** [comment]
@lolgear done

**Comment by lolgear** [comment]
I neither like 1 as a length of desired string nor 2 as a max length of string in `strnlen`.
Maybe it is better to use macros here or const/static?
I don't know, it is weird :/

**Comment by ffried** [comment]
What's wrong with these values? 1 as length is simply `malloc(size * 1)`. And since `strnlen` will have to check for `\0` in the string, 2 as max len will make sure it doesn't look too far but gives up whenever the string is any longer than 1. Since this is an arbitrary choice, I've added the comment there.

The first is just "normal" IMHO. The second is arbitrary, but only for this specific location, so macros or static const won't do any good either. That's what comments are for.

**Comment by OSSPolice** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">The library files were changed, but the tests remained unmodified. Consider updating or adding to the tests to match the library changes.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by lolgear** [comment]
@ffried 
Fine, right.

I think about "pure" solution here.
1. Check first symbol of string for not to be null.
2. Check first symbol to be '/'.
3. Check second symbol to be null.


```c
// If I am correct about comparison here. Not Sure
if (name != '\0' && name == '/' && *(++name) == '\0') {}
```

**Comment by lolgear** [comment]
@ffried 
Ah!
I see, you `calloc` 1s instead of `sizeof(char)` :)

**Comment by ffried** [comment]
@lolgear You're actually right. We could express these as `(char *)calloc(_appLen + 1, sizeof(char))`... That sounds better indeed. Let's change that.

**Comment by lolgear** [comment]
@ffried 
What about C pointer arithmetics?
Do you admire it? :)

**Comment by ffried** [comment]
@lolgear What about it? 🙂

**Comment by lolgear** [comment]
@ffried 

```c
// If I am correct about comparison here. Not Sure
if (name != '\0' && name == '/' && *(++name) == '\0') {}
```

**Comment by ffried** [comment]
@lolgear I think it would be correct. But from a readability perspective much worse than `strnlen(name, 2) == 1` 😉

**Comment by lolgear** [comment]
@ffried 
So, let's merge it?

**Comment by ffried** [comment]
@lolgear Fine by me. Let's wait for the CI 🙂

**Comment by sushichop** [comment]
LGTM👍
Now I found another banned API(function). So I'll create a PR for it later.

**Pull request merged**
