### PR TITLE
Fixed debug symbols stripping

### PR DESCRIPTION
**Pull request by radulov**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/CocoaLumberjack/)
* [x] I have searched for a similar pull request in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have added the required tests to prove the fix/feature I am adding
* [x] I have updated the documentation (if necesarry)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / reffers to the following issues: ...

### Pull Request Description

This pull request changes allow to strip debug symbols for framework users.
Stripping debug symbols decrease application size.
...

### CODE REVIEW

**Comment by rivera-ernesto** [comment]
AFAIK debug symbols will get stripped from AppStore builds automatically.

On the other hand removing the symbols won't allow debugging for developers.

**Comment by radulov** [comment]
Developers use debug configuration, so they have ability to check DSYMs. For custom release builds need to strip all debug symbols in case of its useless.

**Comment by rivera-ernesto** [comment]
To analyze Release/Production crash reports you still need to upload those symbols to your crash report service.

If you check your release binaries, symbols (dSYM) files are never included in there. So they don't account into your app's size.

**Comment by radulov** [comment]
Yes, dSYM files never included in release build, but framework release binaries contains debug symbols. You can easy check it using command "nm". For example output(release binary) before my changes:
[Before.txt](https://github.com/CocoaLumberjack/CocoaLumberjack/files/965222/Before.txt)
and after:
[After.txt](https://github.com/CocoaLumberjack/CocoaLumberjack/files/965221/After.txt)

**Comment by rivera-ernesto** [comment]
> but framework release binaries contains debug symbols

Which isn't bad at all. You get the smaller final app and have the ability to analyze framework's crashes.

**Comment by radulov** [comment]
But how binaries with additional symbols can be smaller? And even without debug symbols we can analyze crashes in release builds, for example in Fabric system. At the same time, crash log for end users of our products will not contain real names.

**Comment by rivera-ernesto** [comment]
I think we discussed everything already:

- You're app won't be bigger because of symbols.
- You need symbols to analyze production crashes.
- End users won't have the symbols, so crashes won't contain "real names".

Closing this for now.

**Pull request closed without merging**
