### PR TITLE
Add Stale Bot configuration

### PR DESCRIPTION
**Pull request by ffried**
Add configuration file for stale bot.

### CODE REVIEW

**Comment by ffried** [comment]
@bpoplauschi @rivera-ernesto This should add the necessary configuration for [Stale Bot](https://probot.github.io/apps/stale/). Can you check whether you're ok with the config and then merge this and enable the integration? This checks another task in #941. 🙂

**Comment by bpoplauschi** [comment]
Looking good @ffried.

I still want to look at the open issues, but this should give me 7 days to do so :)

**Comment by ffried** [comment]
This just adds the config file. So if you need more time, you can simply not activate the bot just yet. 😉

Also, I don‘t know if it‘ll go through all open issues and mark them as stale right now, or if it just starts counting the days as of now.

**Comment by bpoplauschi** [comment]
@ffried 

> This just adds the config file. So if you need more time, you can simply not activate the bot just yet. 😉

Let's activate it. This will push me to do the triage, then maybe add `Important` or `Blocker` labels for those that need to remain open.

> Also, I don‘t know if it‘ll go through all open issues and mark them as stale right now, or if it just starts counting the days as of now.

This is something I don't know either. But probably does, because otherwise how it will work?

**Comment by ffried** [comment]
@bpoplauschi 
> This is something I don't know either. But probably does, because otherwise how it will work?

It could also just start with today as day 0 and mark the current issues als `Stale` in 60 days. 🤷‍♂️

**Comment by bpoplauschi** [comment]
I would just start it and let it work as it is, basically mark all the issues older than 60 days as Stale. Let's try it

**Comment by ffried** [comment]
According to my overflowing mailbox, the bot did indeed just mark (almost) all issues as `Stale`... 😆

**Comment by bpoplauschi** [comment]
:) most of them were older than 60 days. I am going through them - let's see how that goes.

**Comment by ffried** [comment]
Yep, looks good. If you need any support, let me know!

**Comment by bpoplauschi** [comment]
Actually I do. Let's bring in the rest of the team

@CocoaLumberjack/collaborators we've enabled the Stable bot that has marked most of our open issues as stale (they are old and not updated).
I am going through them one by one:
- closing the ones that are resolved or too old or not applicable anymore ...
- marking the ones that need to remain open with the Labels __Blocker__ or __Important__

I would appreciate if you guys could do the same, just pick a few or as many as you can and try to do the same.

**Comment by bpoplauschi** [comment]
@ffried appreciate your help on triaging through the issues - we're halfway there

**Comment by ffried** [comment]
@bpoplauschi I think we're through all current Stale issues!!! 🎉

**Comment by bpoplauschi** [comment]
Thanks @ffried for your help. Definitely the pressure from Stale-bot helped :) Glad we reduced the issues and it's easier to go through them now

**Pull request merged**
