### PR TITLE
Prepare release 3.6.2 #trivial

### PR DESCRIPTION
**Pull request by ffried**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/CocoaLumberjack/)
* [x] I have searched for a similar pull request in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have added the required tests to prove the fix/feature I am adding
* [x] I have updated the documentation (if necessary)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / refers to the following issues: n/a

### Pull Request Description

Prepares release 3.6.2.

### CODE REVIEW

**Comment by ffried** [comment]
@CocoaLumberjack/collaborators I think we're ready for another small release, so that we can use `master` for changes for the next Xcode / platform releases (e.g. #1153).

**Comment by ffried** [comment]
@sushichop Just in time for my "guess" on the release date in changelog. Thanks!

I'll create the GH-Release and the CocoaPods release now.

**Comment by sushichop** [comment]
Nice🎉

**Comment by ffried** [comment]
And version 3.6.2 is live.

**Pull request merged**
