### PR TITLE
Swift improvements

### PR DESCRIPTION
**Pull request by MaddTheSane**
These improvements help make the Swift additions to CocoaLumberjack behave better, as well as fixing some bugs.

### CODE REVIEW

**Comment by bpoplauschi** [comment]
Looks good to me, but since I'm not yet a valid Swift practitioner, I will wait for @rivera-ernesto and @dvor to look at this PR. Anyway, @MaddTheSane thanks for working on this.

**Comment by rivera-ernesto** [comment]
Looks good!

By the way would you like to be a maintainer? Just by looking over Swift compatibility would be enough. Off course you could participate in any issue/pull request and we would continue to take a look at Swift as well.

**Comment by MaddTheSane** [comment]
I wouldn't mind being a maintainer, even if it is only over Swift code.

**Comment by rivera-ernesto** [comment]
Perfect! @robbiehanson could you add @MaddTheSane as a maintainer?

**Comment by bpoplauschi** [comment]
@robbiehanson could you respond to this, please?

**Comment by bpoplauschi** [comment]
@robbiehanson hey man, could you help us out with this? We should bring this guy on board.

**Comment by rivera-ernesto** [comment]
I don't think he gets any mentions' notification. We should try contacting him directly but I can't find a valid email address.

**Comment by robbiehanson** [comment]
> could you add @MaddTheSane as a maintainer?

Added.

**Comment by rivera-ernesto** [comment]
Thanks @robbiehanson, it would be also good to have the permissions to freely add maintainers. I think GitHub has improved organization permissions, so you should be able to give us that permission while keeping owner privileges for yourself.

**Pull request merged**
