### PR TITLE
Add pre-packaged formatter that includes file name and line number. 

### PR DESCRIPTION
**Pull request by jasperblues**
* Save time setting up CocoaLumberjack
* Serve as documentation on how to create own custom format.

### CODE REVIEW

**Comment by bpoplauschi** [comment]
This should probably be set as an example rather than included in the library, IMO.

**Comment by jasperblues** [comment]
@bpoplauschi Its up to you. I presented my justification in #403. ie, since its so commonly asked for, why make it necessary to read the docs on creating a formatter, implement one, plug it in,  and end up copy/pasting it between projects.

**Comment by rivera-ernesto** [comment]
I think we can add those as long as they are not automatically imported by the main header files.

Also as @bpoplauschi says the formatter should be demonstrated somewhere to make it easy to test. To avoid a big number of bum demos we should probably add it to one of the existing formatter-related demos. Could you do that?

**Comment by bpoplauschi** [comment]
@jasperblues could you update the PR with our latest comments?

**Comment by bpoplauschi** [comment]
@jasperblues any updates?

**Comment by jasperblues** [comment]
Let's close this PR. I'm no longer interested in this feature. At the time I thought it might be useful for others. Not sure if this is the case, but presently I don't have sufficient time to work on this.

**Comment by bpoplauschi** [comment]
Ok. Thanks anyway.

**Pull request closed without merging**
