### PR TITLE
iOS bitcode support for carthage

### PR DESCRIPTION
**Pull request by ichibod**
See https://github.com/Carthage/Carthage/issues/535#issuecomment-143182432

### CODE REVIEW

**Comment by kballard** [comment]
You don't need to do anything here. Carthage 0.9.4 will automatically handle bitcode properly.

**Comment by ichibod** [comment]
Current release according to github is 0.9.3

**Comment by kballard** [comment]
Yep, that's why I said "will". Sorry, I should have been more clear. Current `master` of Carthage includes support for setting `BITCODE_GENERATION_MODE` properly, and Carthage/Carthage#853 (which is milestones for 0.9.4) handles the `*.bcsymbolmap` files properly when archiving.

**Comment by ichibod** [comment]
Thanks for the tip

**Comment by rivera-ernesto** [comment]
So is this good to merge yet?

**Comment by ichibod** [comment]
I would say no, as it will compile, it will not distribute until @kballard's PR is added to Carthage, however, this PR will be rendered useless by that change as well, so I will be closing, and waiting for his 0.9.4 update.

**Comment by Kirow** [comment]
Any way to make archive using carthage 0.9.3?
After ```carthage update``` there is no project checkout for CocouLumberjack to add ```BITCODE_GENERATION_MODE```

**Comment by kballard** [comment]
@Kirow honestly, the easiest way to make this work is to use Xcode 6.4 to build Carthage/Carthage#853 (`make package` will give you the installer package, make sure to run it with `DEVELOPER_DIR` pointing at your Xcode 6.4 installation).

**Comment by rivera-ernesto** [comment]
I haven't used Carthage but this reminds me of Apple discouraging distributing of compiled Swift code as generated binary code is not being fully compatible between Swift revisions. But then the library is mostly Objective-C...

**Comment by Kirow** [comment]
@kballard Thx for advice, however I was looking for some one-click way to fix this issue. If there is no such way at this moment, then I will wait for carthage 0.9.4. Hope it will solve the problem.

**Comment by kballard** [comment]
Good news, Carthage 0.9.4 was just released this morning!

**Pull request closed without merging**
