### PR TITLE
upgrade schemes

### PR DESCRIPTION
**Pull request by diederich**
Just a version bump to get rid of the warning

### CODE REVIEW

**Comment by diederich** [comment]
🙏

**Comment by bpoplauschi** [comment]
@diederich Thanks a lot for showing interest and contributing to CocoaLumberjack! Even tough it’s been a while, we would like to invite you to become a maintainer – no pressure to accept! You can pitch in with what seems comfortable: comment on open issues/PRs, triage, improve documentation, write your own PRs. See a broader discussion here #941. Let me know if you are interested.

**Comment by diederich** [comment]
Hey @bpoplauschi - thanks for the invite. I'm very happy to see movement here - nice job!
I'm using CocoaLumberjack in most of my projects, so I'll be happy to keep contributing PRs when they come up.

**Comment by bpoplauschi** [comment]
@diederich Great. I sent you an invitation to our org.

**Pull request merged**
