### PR TITLE
Update to Swift 1.2

### PR DESCRIPTION
**Pull request by MaddTheSane**
This updates make CocoaLumberjack compatible with Swift 1.2.

### CODE REVIEW

**Comment by MaddTheSane** [comment]
Fixes #491.

**Comment by mcmurrym** [comment]
I see you are calling logText instead of passing it. If you want to avoid calling it you can change `@autoclosure` to `@autoclosure(escaping)` This will allow the passing of the closure without calling it. :) I would have said this earlier but I just learned about it.

**Comment by MaddTheSane** [comment]
@mcmurrym: Done.

**Comment by bpoplauschi** [comment]
Great, @MaddTheSane. I will merge this into the `swift_support` branch since I'm not sure when we will release the Swift version (2.1).

**Comment by bpoplauschi** [comment]
Merged. I will close this PR.

**Comment by rivera-ernesto** [comment]
Is the last commit failing because Travis is not updated?

**Comment by bpoplauschi** [comment]
It's failing because of some unit test which fails randomly. I need to revisit those. The stuff on the `swift_support` branch looks ok.

**Pull request closed without merging**
