### PR TITLE
Follow-up to add annotations to `DDOSLogger`

### PR DESCRIPTION
**Pull request by sushichop**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/CocoaLumberjack/)
* [x] I have searched for a similar pull request in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have added the required tests to prove the fix/feature I am adding
* [x] I have updated the documentation (if necessary)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / refers to the following issues: #1243
Since `sharedInstance` is a  class property, it seems that we need to add the annotation to `DDOSLogger.m` , not `DDOSLogger.h`.

### CODE REVIEW

**Comment by ffried** [comment]
@sushichop Are we sure this isn't a temporary hiccup with the beta of Xcode 13? It feels weird having to annotate the implementation file 🤔

**Comment by sushichop** [comment]
@ffried 
Good point! Indeed, Xcode 12.5 doesn't seem to show this warning... I just confirmed it. 
(FYI. It still shows up in Xcode 13.0 beta5.)

Shall we wait and see until Xcode 13.5 GM?

**Comment by ffried** [comment]
@sushichop Yea, I'd simply keep the PR around in case it's still necessary once Xcode 13 goes into GM state.
Maybe a feedback report would be a good idea as well - possibly even referencing this issue. 😉

**Comment by LowAmmo** [comment]
Looking at the issue... It seems to be a legit problem - just Xcode 13 seems to be better about static analysis to detect these types of possible problems.

**Review by LowAmmo — APPROVED** [review]

**Comment by ffried** [comment]
@LowAmmo I'm still not convinced that it's a real problem. The static sharedInstance is nested inside a class that's correctly annotated. Thus the sharedInstance storage isn't reachable on older platforms since all access paths are sufficiently annotated. Or am I missing something here?

**Comment by LowAmmo** [comment]
Yes, I would agree it's not a "real problem" - it's not going to cause a crash, etc, because it wouldn't get used outside of the DDOSLogger.m anyway.

But, it is a warning, and we  try to get our projects down to 0 warnings - to help ensure that when a more legit/dangerous warning comes up, our developers actually notice it.

(Admittedly, it might be a little OCD... I just really like to build and see no warnings! 😄 )

**Comment by LowAmmo** [comment]
I mean...this is a focused audience of developers worried about logging...

I guess it's safe to assume I'm not the only one that's a little bit OCD on these things... 😉

**Comment by ffried** [comment]
@sushichop Is this still an issue with the RC of Xcode 13?

**Comment by sushichop** [comment]
@ffried Yes, this is still an issue with Xcode 13.0 RC (13A233) unfortunately...

**Review by ffried — APPROVED** [review]

**Comment by ffried** [comment]
Well then, let's get this in...

**Pull request merged**
