### PR TITLE
Add support for Swift 5.2 and Xcode 11.4

### PR DESCRIPTION
**Pull request by ffried**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/CocoaLumberjack/)
* [x] I have searched for a similar pull request in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have added the required tests to prove the fix/feature I am adding
* [x] I have updated the documentation (if necessary)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / refers to the following issues: -

### Pull Request Description

This makes a few adjustments that are necessary for Swift 5.2 and Xcode 11.4 - especially for SPM

- Symlink workaround now produces a warning -> move headers into subfolder, change to fully qualified imports and remove symlinks
- Cleanup Header import order - errors first, then 3rd party, then ours
- Change module import statement to normal header import in CocoaLumberjackSwift Framework header (discouraged as mentioned in Xcode 11.4 release notes)
- Update Package.swift for Swift 5.2
- Fix gitignore to not ignore our Lumberjack.xcodeproj

### CODE REVIEW

**Comment by OSSPolice** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">The library files were changed, but the tests remained unmodified. Consider updating or adding to the tests to match the library changes.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">The Carthage project was modified but CocoaPods podspec wasn’t. Did you forget to update the podspec?</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by bpoplauschi** [comment]
Looks good to me too. Thanks @ffried.
My only question: will this work for all our installation options, especially CocoaPods without `use_frameworks!` - I remember some issues with using imports like `#import <CocoaLumberjack/Header.h>` vs `#import "Header.h"

**Comment by ffried** [comment]
@bpoplauschi I'm not too sure, since I'm not using CocoaPods. On the other hand, I've not changed any imports (except in `CLIColor.m`). They were already `<CocoaLumberjack/Header.h>`. I've just reordered them. My first approach was to use double quoted imports in the implementation files, but since SPM recommends creating a dedicated folder inside the `include` folder and we already had the angle brackets imports (almost) everywhere, I've opted for this.
Travis seems to be happy, SPM builds worked, local (Xcode) builds worked - so I'm pretty sure this will be fine.

**Comment by bpoplauschi** [comment]
I agree @ffried. If any issues pop-up we will fix them, but indeed with all the checks we have we should be good.

**Comment by ffried** [comment]
@bpoplauschi Speaking of it, just saw that Travis actually failed (`pod lib lint`) but never reported that back to the PR. Podspec was missing the required patterns to find the moved header files. Fixed that now.

Any idea why Travis no longer reports back?

**Comment by sushichop** [comment]
Nice fix.

> Any idea why Travis no longer reports back?

I'm not sure what is a root cause, but it may be worth trying [this](https://github.com/travis-ci/travis-ci/issues/10204). Organization owners(I'm not an owner) can re-enable settings.
Any idea?

**Comment by sushichop** [comment]
I re-synchronized GitHub PR and Travis-CI.
Now everything works fine🙂

**Comment by bpoplauschi** [comment]
Thanks @sushichop - I was about to look into that

**Comment by sushichop** [comment]
Let's wait for CI test result about #1131 over coffee🙂

**Pull request merged**
