### PR TITLE
added a very basic os_log (unified logging) logger

### PR DESCRIPTION
**Pull request by acacio88**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/CocoaLumberjack/)
* [x] I have searched for a similar pull request in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [ ] I have added the required tests to prove the fix/feature I am adding
* [ ] I have updated the documentation (if necesarry)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / reffers to the following issues: 
https://github.com/CocoaLumberjack/CocoaLumberjack/issues/765

### Pull Request Description

I added a first draft of a logger which uses the new os_log API (https://developer.apple.com/reference/os/logging).

The aim is to be future proof and most of all to be able to log more than 1024chars in the device logs (see: https://github.com/CocoaLumberjack/CocoaLumberjack/issues/765)

### CODE REVIEW

**Comment by rivera-ernesto** [comment]
Can you take a look at the Travis error?

https://travis-ci.org/CocoaLumberjack/CocoaLumberjack/builds/209397735

**Comment by acacio88** [comment]
thanks for the merge @rivera-ernesto, can the version be bumped to 3.2 ? Since I reference this pod as a dependency in a podspec, refering to the git master is not possible and a released version is needed.

**Comment by rivera-ernesto** [comment]
Again, I leave releases to @bpoplauschi .

**Comment by acacio88** [comment]
@bpoplauschi did you by any chance have time to look into this ?

**Comment by bpoplauschi** [comment]
Not yet guys, I'm a bit busy right now, but I will take a look soon.

**Comment by acacio88** [comment]
bump @bpoplauschi  :) ?

**Comment by judos** [comment]
Very useful change. Thanks for doing the fix @acacio88.
We would also require this change. Can you release a newer version @bpoplauschi ?

**Comment by bpoplauschi** [comment]
Sorry guys. I'll make it up with a new release :)

**Comment by bpoplauschi** [comment]
Ok, version 3.2.0 is available. Enjoy :) and again sorry for the delay

**Comment by judos** [comment]
Cool, thanks @bpoplauschi

**Pull request merged**
