### PR TITLE
Swift synthax updated for Swift 2.2

### PR DESCRIPTION
**Pull request by antoinelamy**

### CODE REVIEW

**Comment by antoinelamy** [comment]
Looks like there is a bug in xctool making that build fail. The bug appears to be fixed in the release 0.2.9 of xctool. Not exactly sure why the xctool version is not printed in the travis console though.
https://github.com/facebook/xctool/issues/684

**Comment by antoinelamy** [comment]
From the [blog](https://blog.travis-ci.com/2016-03-23-xcode-image-updates), it seems that the running version of xctool is 0.2.8. If anyone have a way around this issue please let me know.

**Comment by rivera-ernesto** [comment]
Seems like we have another #704 duplicate ;)

**Comment by antoinelamy** [comment]
@rivera-ernesto Sorry I didn't see it with no open PR + all those warnings burning my eyes ;)

**Comment by rivera-ernesto** [comment]
Hehe, I know.

**Pull request closed without merging**
