### PR TITLE
Remove swift file from normal iOS framework

### PR DESCRIPTION
**Pull request by nrbrook**
Fixes https://github.com/CocoaLumberjack/CocoaLumberjack/issues/658

### CODE REVIEW

**Comment by sinoru** [comment]
This will broke other swift project. How about revert #647

**Comment by nrbrook** [comment]
This does need resolving as otherwise non-swift projects require the swift dylib which adds to the bundle size. There could perhaps be two separate framework targets.

**Comment by rivera-ernesto** [comment]
I think that two targets makes sense as less projects stay Objective-C-only.

**Comment by sinoru** [comment]
So revert #647 (db6a623) that merges CocoaLumberjack, CocoaLumberjackSwift can solve the issue. I think.

**Comment by nrbrook** [comment]
I've just added a new commit which adds a separate swift framework target. I've tested on both swift and non-swift projects. There is no test target for the non-swift framework though.

**Comment by rivera-ernesto** [comment]
The advantage of (partially) reverting #647 would be ensuring that most users won't even notice something happened in between.

**Comment by sinoru** [comment]
@rivera-ernesto Right. If create new target or anything else, It will make users notice it.

**Comment by rivera-ernesto** [comment]
@sinoru Could you try to make a pull request for that?

**Comment by sinoru** [comment]
@rivera-ernesto Okay. I make it right now.

**Comment by rivera-ernesto** [comment]
And thanks for pointing out this issue @nrbrook!

**Comment by sinoru** [comment]
I just create new pull request (#690)

**Comment by rivera-ernesto** [comment]
@nrbrook Please give #660 a try and tell us if that works for you.

**Pull request closed without merging**
