### PR TITLE
Update to Swift 2.2: Change `__FUNCTION__` to `#function`, `__FILE__` to `#file`

### PR DESCRIPTION
**Pull request by MarkQSchultz**
and `__LINE__` to `#line`

### CODE REVIEW

**Comment by MarkQSchultz** [comment]
Ref #702

**Comment by rivera-ernesto** [comment]
Thanks!

**Comment by rivera-ernesto** [comment]
I think we could release this even before Xcode 7.3 becomes mandatory. People with older version could just keep using the older version.

What do you think @bpoplauschi ?

**Comment by MaddTheSane** [comment]
Agreed. Also note that the old-style `__FILE__`, etc… won't work on Swift 3.

**Comment by bpoplauschi** [comment]
Not sure what to do here. We should see what other projects have done.

**Comment by bpoplauschi** [comment]
I see Alamofire has switched to Xcode 7.3 as a requirement since version 3.3.0. I think we can do the same. Release a new version that requires Swift 2.2+ and Xcode 7.3+.

**Comment by bpoplauschi** [comment]
Guys, I have created a 2.3.0 release with all the latest changes, that requires Xcode 7.3 and Swift 2.2. Hope this helps

**Comment by rivera-ernesto** [comment]
Thanks a lot!

**Pull request merged**
