### PR TITLE
Get rid of separate CocoaLumberjackSwift.framework for most platforms

### PR DESCRIPTION
**Pull request by kballard**
For iOS, watchOS, and tvOS, we can support Swift directly with CocoaLumberjack.framework instead of having a separate CocoaLumberjackSwift.framework. OS X still requires CocoaLumberjackSwift.framework because it has a deployment target of 10.7 but Swift requires 10.9 or later.

### CODE REVIEW

**Comment by bpoplauschi** [comment]
I think those changes might break compatibility with the existing installs, so after our recent releases have also done this, not sure it this is wanted.
@rivera-ernesto what do you think?

**Comment by rivera-ernesto** [comment]
I think that anything that simplifies the project is good. Let's prepare a 2.3.0 release allowed to break some small things like this and a default `ddLogLevel` (#648) in order to improve the library.

**Comment by rivera-ernesto** [comment]
As for this pull request in particular, I think it should be broken into two different pull requests as modifying the Swift "macros" is not what this pull request describes.

Let's just keep the merge frameworks commits here.

**Comment by DD-P** [comment]
If there are backward-incompatible changes (e.g. to the .xcodeproj), would a 3.0.0 version be preferred to maintain semantic versioning?

SemVer was being advocated in the past (#542).

**Comment by kballard** [comment]
The macro changes actually are backwards-compatible. This is why I left `SwiftLogMacro` intact and just marked it as deprecated. The project changes are the backwards-incompatible part.

I almost left the `CocoaLumberjackSwift` modules intact as stubs, to preserve backwards compatibility, but I took them out entirely because I figured that was just too confusing. CocoaLumberjack already doesn't do a good job of explaining Swift support, so I figured it was better to kill the CocoaLumberjackSwift framework entirely so people wouldn't unnecessarily import it. It also speeds up the build a bit (because building those stub frameworks does take time).

**Comment by rivera-ernesto** [comment]
@DD-P only v.v.X versions really need to be minor. We're not rewriting most classes as we did for 2.0.0 and we don't want to be in version 18 in a year, so I think it's ok to make a 2.3.0 release that requires some small migration and only for users that installed manually.

@kballard The macro changes look good, it is just that I think they should be made in a separate pull request to make it cleaner/easier to review/discuss/document.

**Comment by kballard** [comment]
Ok I'll split it out.

**Comment by kballard** [comment]
PR updated, #649 filed for the Swift cleanup.

**Comment by rivera-ernesto** [comment]
Thanks!

**Pull request merged**
