### PR TITLE
Add SWIFT_VERSION in podspec to allow compilation on Xcode8.

### PR DESCRIPTION
**Pull request by busce**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/CocoaLumberjack/)
* [x] I have searched for a similar pull request in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have added the required tests to prove the fix/feature I am adding
* [x] I have updated the documentation (if necesarry)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

### Pull Request Description

Add `SWIFT_VERSION = 2.3` in the Cocoalumberjack.podspec file to allow compilation on Xcode8 through Cocoapods.

### CODE REVIEW

**Comment by bpoplauschi** [comment]
I think this setting should be done in the actual project (project level), not forced by Lumberjack. Thoughts?

**Comment by busce** [comment]
@bpoplauschi I change the (*swift) projects settings.

**Comment by davideme** [comment]
Is there any blocker with this PR ?

**Comment by kballard** [comment]
It looks like you're setting SWIFT_VERSION on each target individually. Why not just set it once at the project level?

**Comment by bpoplauschi** [comment]
This PR is no longer applicable. See version 2.4.0 for Swift 2.3 and version 3.0.0 for Swift 3.0.

**Pull request closed without merging**
