### PR TITLE
Version 3.6.1 #trivial

### PR DESCRIPTION
**Pull request by ffried**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/CocoaLumberjack/)
* [x] I have searched for a similar pull request in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [ ] I have added the required tests to prove the fix/feature I am adding
* [ ] I have updated the documentation (if necessary)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / refers to the following issues: -

### Pull Request Description

Prepare a new release v3.6.1

### CODE REVIEW

**Comment by OSSPolice** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">The CocoaPods podspec was modified but the Carthage project wasn’t. Did you forget to update the xcodeproj?</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by ffried** [comment]
@CocoaLumberjack/collaborators I think we've collected a few nice changes for a bugfix release. What do you think?

**Comment by bpoplauschi** [comment]
Agreed @ffried - can you take care of releasing this new version?
Good job everyone @CocoaLumberjack/collaborators

**Comment by ffried** [comment]
@bpoplauschi I've never done a CocoaPods release before. If you can tell me what I need to do there, I can do this as well. I can certainly take care of the GitHub release, though.

**Comment by lolgear** [comment]
@ffried @bpoplauschi 
It is interesting how cocoa pods is handling users and groups.

https://guides.cocoapods.org/making/getting-setup-with-trunk.html

Could anybody in collaborators group make a release via `pod trunk push`?

**Comment by ffried** [comment]
@lolgear CocoaLumberjack lists the collaborators:
image

**Comment by lolgear** [comment]
@ffried 
Not ok. I guess this list is incomplete.

**Comment by ffried** [comment]
@lolgear I'm not sure whether we also need to add all GitHub collaborators to CocoaPods. I'd be perfectly fine with having a few people that are responsible for creating releases.

**Comment by lolgear** [comment]
I'm voting for including @ffried in Maintainers list if he don't mind.

**Comment by sushichop** [comment]
Hi guys! Sorry for late response.

@ffried 
1) Are you interested in releasing CocoaLumberjack 3.6.1 by yourself? If the answer is yes, I think you can wrap up CHANGE LOG and publish release note right now :)
Anyway, we can register it as a CocoaPods library only after release note has been published(CocoaPods library needs GitHub tag info). 
2) And if you want to join into CocoaPods collaborators list, I can add you to it! If you are not familiar with registering CocoaPods library, I'll register it!

Any idea? If you mind it, I'll publish release note and register CocoaPods library from now🙂
Thanks for your contribution these days👍

**Comment by ffried** [comment]
To be honest, I'm not a big fan of CocoaPods. Which is why I have no experience in publishing pods  whatsoever.
Nevertheless we do have CocoaPods as one of our publishing platforms, so we need to support it. I agree with @lolgear that we should add one or two more collaborators to CocoaPods and if you guys vote for me here, I don't mind. If so, I'd just need someone to give me a quick intro on what I need to do to publish a release to CocoaPods.

@sushichop Thanks for the info. I'll quickly create the GitHub release then. Just a sec :)

**Comment by ffried** [comment]
@sushichop Ok, GitHub release is done. What do I need to do for CocoaPods?

**Comment by sushichop** [comment]
@ffried 
Great! First you need to register your information(your email and name) to pod trunk.
See https://guides.cocoapods.org/making/getting-setup-with-trunk.html.

> e.g.
> $ pod trunk register orta@cocoapods.org 'Orta Therox' --description='macbook air'

**Comment by sushichop** [comment]
@ffried 
Next.
Let me know the above info(actually I need only your email).
I'll add you to the pod trunk collaborators list using following command.
> e.g.
> $ pod trunk add-owner CocoaLumberjack yourname@yourdomain

**Comment by ffried** [comment]
@sushichop Done. Email is my GitHub username `@me.com`. 😉

**Comment by sushichop** [comment]
@ffried I added you to the list. Welcome!🙂

The last one. 
You check out master branch commit(3.6.1), then execute next command in order to register a library to pod trunk.

> pod trunk push CocoaLumberjack.podspec

**Note**
**I always check a library works fine by executing `pod lib lint` and integrating master branch with Podfile before registering a library.**

Good luck!

**Comment by sushichop** [comment]
@ffried 

> **I always check a library works fine by executing `pod lib lint` and integrating master branch with Podfile before registering a library.**

This time I have already check the above😉
So all you have to do is `pod trunk push CocoaLumberjack.podspec` this time.

**Comment by ffried** [comment]
@sushichop Thanks.
Push also succeeded:
```
--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  CocoaLumberjack (3.6.1) successfully published
 📅  February 3rd, 17:33
 🌎  https://cocoapods.org/pods/CocoaLumberjack
 👍  Tell your friends!
-------------------------------------------------------------------------------
```

Thanks for the help to get me started here. I hope I remember the steps next time 😆

**Comment by sushichop** [comment]
@ffreid
Congrats🎉

**Comment by bpoplauschi** [comment]
Excelent guys! I got back too late for this :)

**Pull request merged**
