### PR TITLE
Reduce podspec to 2subspecs and remove customized modulemap

### PR DESCRIPTION
**Pull request by sushichop**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/CocoaLumberjack/)
* [x] I have searched for a similar pull request in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have added the required tests to prove the fix/feature I am adding
* [x] I have updated the documentation (if necessary)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / refers to the following issues: #954 

### Pull Request Description

This PR reduces podspec to 2 subspaces(Core and Swift) to simplify usage of CocoaPods and match to Carthage. 
And PR also removes customized modulemap(They needs to be adopted at the same time).

Thanks.

### CODE REVIEW

**Comment by sushichop** [comment]
@ffried 
Oh, approved too fast:) Thanks.

**Comment by ffried** [comment]
@sushichop Looks good to me. Travis will have the last word, though. 🙂

**Comment by OSSPolice** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Any changes to library code should be reflected in the CHANGELOG. Please consider adding a note there about your change.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">The library files were changed, but the tests remained unmodified. Consider updating or adding to the tests to match the library changes.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by sushichop** [comment]
[ci skip]

**Comment by bpoplauschi** [comment]
I have just got to review this PR. Overall looks good, thanks @sushichop 

A few comments to think about:
- per https://guides.cocoapods.org/syntax/podspec.html#public_header_files
> public_header_files
> A list of file patterns that should be used as public headers.
> These are the headers that will be exposed to the user’s project and from which documentation will be generated. When the library is built, these headers will appear in the build directory. If no public headers are specified then all the headers in source_files are considered public.
- so I guess we don't need to specify the `public_header_files` if all the headers from `source_files` will be public. Just a small detail
- From a certain point of view, removing the `modulemap` means people who used `import CocoaLumberjack.DDDispatchQueueLogFormatter` or similar will need to change their code. That means in semantic version words that this should be a major release. I don't think we should be marking the release with a major bump of version (meaning `4.0.0`) but just wanted to state this.
- It's good to have some parity between CocoaPods and Carthage, but it's still not full parity, as Carthage will create 2 frameworks `CocoaLumberjack.framework` and `CocoaLumberjackSwift.framework`. To match exactly, we would need to add a dedicated `CocoaLumberjackSwift.podspec`, but I'm also not sure about this.

Just would like to hear some feedback on these items. Glad that the PR is merged :)

**Comment by bpoplauschi** [comment]
PS: Out of curiosity, ran [objc-diff](https://github.com/mattstevens/objc-diff) between version 3.4.2 and the latest master, we don't have ObjC API differences (just a change of param types from `NSUInteger` to `NSInteger`).

-------

<html>
<head>
<meta charset="utf-8" />
</head>
<body>

<div class="headerFile">
<div class="headerName">CocoaLumberjack.framework/Headers/CocoaLumberjack.h</div>

<div class="differenceGroup">
<div class="difference"><span class="status added">Added</span> CocoaLumberjackVersionNumber</div>
<div class="difference"><span class="status added">Added</span> CocoaLumberjackVersionString</div>
</div>

</div>

<div class="headerFile">
<div class="headerName">CocoaLumberjack.framework/Headers/DDContextFilterLogFormatter.h</div>

<div class="differenceGroup">
<div class="difference"><span class="status modified">Modified</span> -[DDContextWhitelistFilterLogFormatter addToWhitelist:]</div>
<table>
<tr><th></th><th>Declaration</th></tr>
<tr><th>From</th><td class="declaration">- (void)addToWhitelist:(NSUInteger)loggingContext</td></tr>
<tr><th>To</th><td class="declaration">- (void)addToWhitelist:(NSInteger)loggingContext</td></tr>
</table>
<br>
<div class="difference"><span class="status modified">Modified</span> -[DDContextWhitelistFilterLogFormatter removeFromWhitelist:]</div>
<table>
<tr><th></th><th>Declaration</th></tr>
<tr><th>From</th><td class="declaration">- (void)removeFromWhitelist:(NSUInteger)loggingContext</td></tr>
<tr><th>To</th><td class="declaration">- (void)removeFromWhitelist:(NSInteger)loggingContext</td></tr>
</table>
<br>
<div class="difference"><span class="status modified">Modified</span> -[DDContextWhitelistFilterLogFormatter isOnWhitelist:]</div>
<table>
<tr><th></th><th>Declaration</th></tr>
<tr><th>From</th><td class="declaration">- (BOOL)isOnWhitelist:(NSUInteger)loggingContext</td></tr>
<tr><th>To</th><td class="declaration">- (BOOL)isOnWhitelist:(NSInteger)loggingContext</td></tr>
</table>
<br>
<div class="difference"><span class="status modified">Modified</span> -[DDContextBlacklistFilterLogFormatter addToBlacklist:]</div>
<table>
<tr><th></th><th>Declaration</th></tr>
<tr><th>From</th><td class="declaration">- (void)addToBlacklist:(NSUInteger)loggingContext</td></tr>
<tr><th>To</th><td class="declaration">- (void)addToBlacklist:(NSInteger)loggingContext</td></tr>
</table>
<br>
<div class="difference"><span class="status modified">Modified</span> -[DDContextBlacklistFilterLogFormatter removeFromBlacklist:]</div>
<table>
<tr><th></th><th>Declaration</th></tr>
<tr><th>From</th><td class="declaration">- (void)removeFromBlacklist:(NSUInteger)loggingContext</td></tr>
<tr><th>To</th><td class="declaration">- (void)removeFromBlacklist:(NSInteger)loggingContext</td></tr>
</table>
<br>
<div class="difference"><span class="status modified">Modified</span> -[DDContextBlacklistFilterLogFormatter isOnBlacklist:]</div>
<table>
<tr><th></th><th>Declaration</th></tr>
<tr><th>From</th><td class="declaration">- (BOOL)isOnBlacklist:(NSUInteger)loggingContext</td></tr>
<tr><th>To</th><td class="declaration">- (BOOL)isOnBlacklist:(NSInteger)loggingContext</td></tr>
</table>
<br>
</div>

</div>

<div class="headerFile">
<div class="headerName">CocoaLumberjack.framework/Headers/DDDispatchQueueLogFormatter.h</div>

<div class="differenceGroup">
<div class="difference"><span class="status added">Added</span> DDAtomicCountable</div>
<div class="difference"><span class="status added">Added</span> -[DDAtomicCountable initWithDefaultValue:]</div>
<div class="difference"><span class="status added">Added</span> -[DDAtomicCountable increment]</div>
<div class="difference"><span class="status added">Added</span> -[DDAtomicCountable decrement]</div>
<div class="difference"><span class="status added">Added</span> -[DDAtomicCountable value]</div>
<div class="difference"><span class="status added">Added</span> DDAtomicCounter</div>
</div>

</div>
</body>
</html>

**Comment by sushichop** [comment]
@bpoplauschi 

Thanks for your comment. I agree with you totally.

> * so I guess we don't need to specify the `public_header_files` if all the headers from `source_files` will be public. Just a small detail

Yes, definitely! I'll create a PR later to do the above thing.

> * From a certain point of view, removing the `modulemap` means people who used `import CocoaLumberjack.DDDispatchQueueLogFormatter` or similar will need to change their code. That means in semantic version words that this should be a major release. I don't think we should be marking the release with a major bump of version (meaning `4.0.0`) but just wanted to state this.


I agree with you. Developers who build with Carthage or manually needs to change their code a little about `Extensions` podspec. 
e.g. 
  - from `import CocoaLumberjack.DDDispatchQueueLogFormatter` 
  - to `import CocoaLumberjackSwift`

> * It's good to have some parity between CocoaPods and Carthage, but it's still not full parity, as Carthage will create 2 frameworks `CocoaLumberjack.framework` and `CocoaLumberjackSwift.framework`. To match exactly, we would need to add a dedicated `CocoaLumberjackSwift.podspec`, but I'm also not sure about this.

Yes, you are right. To match exactly, CocoaLumberjackSwift.podspec is also needed because CocoaLumberjack project has two target(CocoaLumberjack and CocoaLumberjackSwift), you know.

Or we have another option. I think we also can merge Swift code to CocoaLumberjack target like OHTTPStubs.
https://github.com/AliSoftware/OHHTTPStubs

Or we also can choose the option like Realm(pure Objective-C or Objetive-C/Swift mixed) and RealmSwift(pure Swift) for the distant? future.
https://github.com/realm/realm-cocoa

But I'm not sure which is the best solution, and I also think it is easy that we just add CocoaLumberjackSwift.podspec for now(though I'm not sure it is strongly necessary for developers now...😅

**Comment by bpoplauschi** [comment]
About the last 2, I don't think we need to change anything, but wanted to at least talk about them. :)

**Comment by sushichop** [comment]
> About the last 2, I don't think we need to change anything, but wanted to at least talk about them. :)

I see😃

**Pull request merged**
