### PR TITLE
Fix #433 CocoaLumberjack 2.0.0-rc does not build with Pods

### LINKED ISSUE #433: CocoaLumberjack 2.0.0-rc does not build with Pods
I updated the CocoaLumberjack to 2.0.0-rc from 2.0.0-beta4 and now the project does not build anymore. This are the two errors I get:

```
DDLog.h:344:1: Property with 'retain (or strong)' attribute must be of object type
DDLog.h:539:1: Property with 'retain (or strong)' attribute must be of object type
```

Apparently these lines were changed to point to objects. Is there any specific reason that those properties are marked as strong?

```
@property (nonatomic, DISPATCH_QUEUE_REFERENCE_TYPE, readonly) dispatch_queue_t loggerQueue;
```

### PR DESCRIPTION
**Pull request by bpoplauschi**

### CODE REVIEW

**Comment by rivera-ernesto** [comment]
Thanks!

**Comment by rivera-ernesto** [comment]
We could probably release rc2 after this.

**Comment by bpoplauschi** [comment]
We can release rc2, no problem. I want to make a push and release 2.0 stable in a few days. Not sure if we need to wait for CocoaPods to include Swift support.

Before we release, since we only need to make sure the framework doesn't break and all the non-backward compatible changes are made now, I think we still need:
- make sure we have a working stable unit testing solution. #447 has a bit too many changes and I'm not sure how to follow. I will take care of those in a day or two
- Simplify framework and add Carthage support #446 
- make an example of CocoaLumberjack + swift and test it using CocoaPods 0.36 beta. #405 #400 
- regarding #329 do we need to do anything here before a 2.0 goes out?
- what about #324 ?
- #225 is ongoing, so we don't need to close it
- #53 is a bug which ideally would get fixed, but it's not a showstopper.

**Comment by rivera-ernesto** [comment]
I think that we can release a 2.0.0 as soon as there are no critical bugs and backwards compatibility works. It is a x.0.0 release, so we can always work over it.

Swift could be 2.1.0 and so on.

**Pull request merged**
