### PR TITLE
Bump version to 3.5.2

### PR DESCRIPTION
**Pull request by sushichop**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/CocoaLumberjack/)
* [x] I have searched for a similar pull request in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have added the required tests to prove the fix/feature I am adding
* [x] I have updated the documentation (if necessary)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

### Pull Request Description

I'm in favor of releasing CocoaLumberjack `3.5.2`.
So I bumped version. Could you review this?

### CODE REVIEW

**Comment by OSSPolice** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">The CocoaPods podspec was modified but the Carthage project wasn’t. Did you forget to update the xcodeproj?</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by lolgear** [comment]
@sushichop 
Heh, this PR also has failed test `-testAutomaticLogFileRollingWhenNotReusingLogFiles`.

Something wrong with either environment or master branch.
I caught them in PR #1039 which doesn't contain any logic for FileLogger as this PR.
Also I tried to run tests locally - the same error.

**Comment by ffried** [comment]
@lolgear Yea, this one and `-[DDFileLoggerTests testWriteToFileUnbuffered]` fails, too. Also they seem to crash, since no expectation-failure is logged.

**Comment by sushichop** [comment]
@lolgear @ffried 
Thank you. Now, I was also worried about it. What we can do?🤔

**Comment by ffried** [comment]
Hmm, I don't see any failures locally...

**Comment by sushichop** [comment]
Yes, me too! I don't see any failures locally😭

**Comment by ffried** [comment]
Ah, well now I do, but only on the iOS simulator...

**Comment by lolgear** [comment]
@ffried @sushichop 
Test failed on iPhone SE simulator and also it doesn't fail if it is tested alone.

**Comment by ffried** [comment]
The problem is, that `removeAllLoggers` is async. We remove the created log files immediately afterwards. But by the time the FileLogger tries to cleanup after itself and mark the current file as archived, said file was already deleted by the test cleanup...

**Comment by lolgear** [comment]
@ffried Ah, too much async code...
We can add NSOperation or semaphores for sync-ing.

**Comment by ffried** [comment]
I'm already working on a fix. We just need to sync the internal queue briefly. No big deal. Will test if what I've got works and then create another PR.

**Comment by ffried** [comment]
See #1053...

**Comment by sushichop** [comment]
Thank you, great guys😊
But it's about time that I have to leave here today.. and I'll back to GitHub tomorrow.

Additional info.
Now I can access to CocoaLumberjack' CocoaPods..
Then after several PRs are merged to master branch, I'll do publish a new pods.
Do you agree?

Good nigh...t😪

**Comment by sushichop** [comment]
@lolgear @ffried 
Thanks for your help🙂

**Comment by sushichop** [comment]
Now, I'm just waiting for CI test result...

**Comment by lolgear** [comment]
@sushichop 
Don't wait for result! Drink a coffee, play the guitar/piano/football, read news or even work 😄

**Comment by sushichop** [comment]
@lolgear 
DONE!
I have released `CocoaLumberjack 3.5.2` and registered it to CocoaPods.
https://raw.githubusercontent.com/CocoaPods/Specs/f15358b196191d6f4702efa6aa9c6af99339a41d/Specs/d/1/8/CocoaLumberjack/3.5.2/CocoaLumberjack.podspec.json

**Pull request merged**
