### PR TITLE
Swift support

### PR DESCRIPTION
**Pull request by MaddTheSane**
Update the `swift_support` branch to `master`.

### CODE REVIEW

**Comment by rivera-ernesto** [comment]
Is this ready for merge?

**Comment by MaddTheSane** [comment]
Yes, this is ready to merge.

**Comment by guidomb** [comment]
Not quite ready to be merged as far as Carthage support. I am getting the following errors when updating carthage dependencies (`carthage update`)

```
The following build commands failed:
	CompileSwift normal x86_64 /Users/guidomb/Documents/projects/wolox/WLXBluetoothDevice/Carthage/Checkouts/CocoaLumberjack/Classes/CocoaLumberjack.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
/Users/guidomb/Documents/projects/wolox/WLXBluetoothDevice/Carthage/Checkouts/CocoaLumberjack/Classes/DDLog.h:23:9: error: include of non-modular header inside framework module 'CocoaLumberjack.DDLog'
/Users/guidomb/Documents/projects/wolox/WLXBluetoothDevice/Carthage/Checkouts/CocoaLumberjack/Classes/CocoaLumberjack.swift:17:8: error: could not build Objective-C module 'CocoaLumberjack'
<unknown>:0: error: unable to execute command: Segmentation fault: 11
<unknown>:0: error: swift frontend command failed due to signal (use -v to see invocation)
A shell task failed with exit code 65:
2015-06-15 21:36:02.124 xcodebuild[92623:3342367] [MT] PluginLoading: Required plug-in compatibility UUID E969541F-E6F9-4D25-8158-72DC3545A6C6 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XToDo.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-06-15 21:36:02.125 xcodebuild[92623:3342367] [MT] PluginLoading: Required plug-in compatibility UUID E969541F-E6F9-4D25-8158-72DC3545A6C6 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XcodeColors.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-06-15 21:36:02.125 xcodebuild[92623:3342367] [MT] PluginLoading: Required plug-in compatibility UUID E969541F-E6F9-4D25-8158-72DC3545A6C6 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ObjectGraph.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-06-15 21:36:02.125 xcodebuild[92623:3342367] [MT] PluginLoading: Required plug-in compatibility UUID E969541F-E6F9-4D25-8158-72DC3545A6C6 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/GitDiff.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-06-15 21:36:02.126 xcodebuild[92623:3342367] [MT] PluginLoading: Required plug-in compatibility UUID E969541F-E6F9-4D25-8158-72DC3545A6C6 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/CocoaPods.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-06-15 21:36:02.126 xcodebuild[92623:3342367] [MT] PluginLoading: Required plug-in compatibility UUID E969541F-E6F9-4D25-8158-72DC3545A6C6 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Backlight.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-06-15 21:36:02.127 xcodebuild[92623:3342367] [MT] PluginLoading: Required plug-in compatibility UUID E969541F-E6F9-4D25-8158-72DC3545A6C6 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal x86_64 /Users/guidomb/Documents/projects/wolox/WLXBluetoothDevice/Carthage/Checkouts/CocoaLumberjack/Classes/CocoaLumberjack.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
```

**Comment by guidomb** [comment]
Scheme `CocoaLumberjackSwift` is not building due to compilation error. If we comment the `DDLegacyMacros.h` import in file `DDLog.h` it works but probably that is not the way to go.

Check it out by running

```
xcodebuild -scheme CocoaLumberjackSwift -project Lumberjack.xcodeproj
```

**Pull request merged**
